name: async
version: 0.1.7+201305271411
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Asynchronous operations
homepage: https://github.com/mezoni/async
dev_dependencies:
  unittest: any
  yaml: any
