name: async
version: 0.1.6+201305171753
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Asynchronous operations
homepage: https://github.com/mezoni/async
dependencies:
  yaml: any
dev_dependencies:
  unittest: any
